USE [master]
GO

/****** Object:  Database [SSIS_PROJECT_STA]    Script Date: 03/06/2022 20:45:03 ******/
CREATE DATABASE [SSIS_PROJECT_STA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SSIS_PROJECT_STA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SSIS_PROJECT_STA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SSIS_PROJECT_STA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SSIS_PROJECT_STA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SSIS_PROJECT_STA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET ARITHABORT OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET  MULTI_USER 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SSIS_PROJECT_STA] SET  READ_WRITE 
GO


